### PR TITLE
toOrdinal: added special behavior for numbers ending with 11, 12 and 13. Fixes #7

### LINKED ISSUE #7: Wrong endings for ordinal numbers from 11 to 13
Converter returns ordinal numbers with wrong endings:
```javascript
converter.toOrdinal(11); // => “11st”
converter.toOrdinal(12); // => “12nd”
converter.toOrdinal(13); // => “13rd”
```
But should be 11**th**, 12**th**, 13**th**.

### PR DESCRIPTION
**Pull request by pilyugin**
toOrdinal: added special behavior for numbers ending with 11, 12 and 13. Fixes #7

### CODE REVIEW

**Comment by marlun78** [comment]
Thanks for contributing, I really appreciate it!! Do you mind if I add you to a contributors list?

**Comment by marlun78** [comment]
Can I add you as: `"Aleksey Pilyugin (https://github.com/pilyugin)"`

**Comment by pilyugin** [comment]
I don't mind. Thanks =)

**Comment by marlun78** [comment]
Version 1.2.2 has now been released. Thanks again for the help!

**Pull request merged**
