### PR TITLE
Fix error when global `isFinite` is undefined

### PR DESCRIPTION
**Pull request by jeremiahrhall**
Hi there!

I ran into an issue using this package with PhantomJS. Apparently, `isFinite` is not defined in the global scope or on `Number` in PhantomJS so, this change just defines a simple polyfill for that case.

### CODE REVIEW

**Comment by marlun78** [comment]
Thank you for the PR! I'll take a closer look during the weekend.

**Comment by chris-garrett** [comment]
@marlun78 Any progress on this PR? This fix allows me to use this package in IE which unfortunately is a requirement for me. Thanks!

**Comment by marlun78** [comment]
Sorry guys, I've been super busy lately. I'll do it during the weekend.

**Comment by marlun78** [comment]
I chose a slightly different implementation, but thanks for the PR. 
This issue was resolved in `f33ba917abfbc625e2cc1e1d46439caf15d284b6`.

**Comment by marlun78** [comment]
@jeremiahrhall @chris-garrett Please let me know if this didn’t solve your issues!

**Pull request closed without merging**
